services:
  #################################################################
  #                           DATABASES                           #
  #################################################################
  user-db:
    image: postgres:15
    container_name: user-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: userpass
      POSTGRES_DB: user_db
    volumes:
      - user_db_data:/var/lib/postgresql/data
    networks:
      - socialnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d user_db"]
      interval: 5s
      timeout: 3s
      retries: 30
    # Optional host access:
    ports:
      - "5433:5432"

  post-db:
    image: postgres:15
    container_name: post-db
    environment:
      POSTGRES_USER: post
      POSTGRES_PASSWORD: postpass
      POSTGRES_DB: post_db
    volumes:
      - post_db_data:/var/lib/postgresql/data
    networks:
      - socialnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U post -d post_db"]
      interval: 5s
      timeout: 3s
      retries: 30
    ports:
      - "5434:5432"

  feedback-db:
    image: postgres:15
    container_name: feedback-db
    environment:
      POSTGRES_USER: feedback
      POSTGRES_PASSWORD: feedbackpass
      POSTGRES_DB: feedback_db
    volumes:
      - feedback_db_data:/var/lib/postgresql/data
    networks:
      - socialnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U feedback -d feedback_db"]
      interval: 5s
      timeout: 3s
      retries: 30
    ports:
      - "5435:5432"

  message-db:
    image: postgres:15
    container_name: message-db
    environment:
      POSTGRES_USER: notify
      POSTGRES_PASSWORD: notifypass
      POSTGRES_DB: message_db
    volumes:
      - message_db_data:/var/lib/postgresql/data
    networks:
      - socialnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U notify -d message_db"]
      interval: 5s
      timeout: 3s
      retries: 30
    ports:
      - "5436:5432"

  #################################################################
  #                           CACHES / QUEUES                     #
  #################################################################
  redis-feed:
    image: redis:7
    container_name: redis-feed
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_feed_data:/data
    networks:
      - socialnet
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 30

  redis-message:
    image: redis:7
    container_name: redis-message
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_message_data:/data
    networks:
      - socialnet
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 30

  redis-feedback:
    image: redis:7
    container_name: redis-feedback
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_feedback_data:/data
    networks:
      - socialnet
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 30

  kafka:
    image: confluentinc/cp-kafka:7.7.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: "1"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "0"
    networks:
      - socialnet
    volumes:
      - kafka_data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 20s

  #################################################################
  #                           MINIO / S3                          #
  #################################################################
  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - socialnet
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9000/minio/health/ready || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30

  #################################################################
  #                   CORE MICROSERVICES                         #
  #################################################################
  user-service:
    container_name: user-service
    build: ./services/user-service
    environment:
      APP_PORT: ":8081"

      DB_HOST: user-db
      DB_PORT: "5432"
      DB_USER: user
      DB_PASSWORD: userpass
      DB_NAME: user_db
    depends_on:
      user-db:
        condition: service_healthy
    networks:
      - socialnet
    ports:
      - "8081:8081"

  post-service:
    container_name: post-service
    build: ./services/post-service
    environment:
      DB_HOST: post-db
      DB_USER: post
      DB_PASSWORD: postpass
      DB_NAME: post_db
      MEDIA_SERVICE_URL: http://minio:9000
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      post-db:
        condition: service_healthy
      kafka:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - socialnet
    ports:
      - "8082:8082"

  feed-service:
    container_name: feed-service
    build:
      context: ./services/feed-service
      dockerfile: Dockerfile
    environment:
      REDIS_HOST: redis-feed
      REDIS_PORT: 6379
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      redis-feed:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - socialnet
    ports:
      - "8083:8083"

  feedback-service:
    container_name: feedback-service
    build: ./services/feedback-service
    environment:
      DB_HOST: feedback-db
      DB_USER: feedback
      DB_PASSWORD: feedbackpass
      DB_NAME: feedback_db
      REDIS_HOST: redis-feedback
      REDIS_PORT: 6379
    depends_on:
      feedback-db:
        condition: service_healthy
      redis-feedback:
        condition: service_healthy
    networks:
      - socialnet
    ports:
      - "8084:8084"

  message-service:
    container_name: message-service
    build: ./services/message-service
    environment:
      DB_HOST: message-db
      DB_USER: notify
      DB_PASSWORD: notifypass
      DB_NAME: message_db
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      REDIS_HOST: redis-message
      REDIS_PORT: 6379
    depends_on:
      message-db:
        condition: service_healthy
      kafka:
        condition: service_healthy
      redis-message:
        condition: service_healthy
    networks:
      - socialnet
    ports:
      - "8085:8085"

  notification-service:
    container_name: notification-service
    build: ./services/notification-service
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - socialnet
    ports:
      - "8086:8086"

  media-service:
    container_name: media-service
    build: ./services/media-service
    environment:
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY: minio
      S3_SECRET_KEY: minio123
    depends_on:
      minio:
        condition: service_healthy
    networks:
      - socialnet
    ports:
      - "8088:8088"

  #################################################################
  #                   API GATEWAY / LOAD BALANCER                 #
  #################################################################
  loadbalancer:
    image: nginx:latest
    container_name: loadbalancer
    depends_on:
      - api-gateway
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    networks:
      - socialnet

  api-gateway:
    container_name: api-gateway
    build: ./services/api-gateway
    environment:
      USER_SERVICE_URL: http://user-service:8081
      POST_SERVICE_URL: http://post-service:8082
      FEED_SERVICE_URL: http://feed-service:8083
      FEEDBACK_SERVICE_URL: http://feedback-service:8084
      MESSAGE_SERVICE_URL: http://message-service:8085
      MEDIA_SERVICE_URL: http://media-service:8088
      NOTIFICATION_SERVICE_URL: http://notification-service:8086
    depends_on:
      user-service:
        condition: service_started
      post-service:
        condition: service_started
      feed-service:
        condition: service_started
      feedback-service:
        condition: service_started
      message-service:
        condition: service_started
      media-service:
        condition: service_started
      notification-service:
        condition: service_started
    networks:
      - socialnet
    ports:
      - "8080:8080"

  #################################################################
  #                    SWAGGER UI FOR DOCS                        #
  #################################################################
  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    container_name: swagger-ui
    depends_on:
      - api-gateway
    ports:
      - "9002:8080"
    environment:
      SWAGGER_JSON: /openapi/combined_openapi.yaml
    volumes:
      - ./combined_openapi.yaml:/openapi/combined_openapi.yaml:ro
    networks:
      - socialnet

networks:
  socialnet:

volumes:
  # Postgres
  user_db_data:
  post_db_data:
  feedback_db_data:
  message_db_data:

  # Redis
  redis_feed_data:
  redis_message_data:
  redis_feedback_data:

  # MinIO
  minio_data:

  # Kafka
  kafka_data:
