root = "."
tmp_dir = "tmp"

[build]
  cmd = "sh -c 'go build -o ./tmp/main ./cmd/main.go && chmod +x ./tmp/main'"
  bin = "tmp/main"
  full_bin = "tmp/main"
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor"]

[log]
  time = true
