receivers:
  otlp:
    protocols:
      http:

processors:
  batch: {}

exporters:
  jaeger:
    endpoint: "jaeger:14250"
    tls:
      insecure: true
  logging:
    loglevel: debug   # <— add

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger, logging]  # <— add logging here too
