server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    # tenant_id: "local"   # leave commented since Loki auth is off

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    # Map Docker metadata to nice labels
    relabel_configs:
      # container name without leading slash -> container="<name>"
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: container

      # compose service -> service="user-service"
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: service

      # compose project -> project="<your compose project>"
      - source_labels: ['__meta_docker_container_label_com_docker_compose_project']
        target_label: project

      # log stream stdout/stderr
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: stream

      # image -> image="repo:tag"
      - source_labels: ['__meta_docker_image']
        target_label: image

    pipeline_stages:
      - docker: {}     # IMPORTANT: keep it as an object
