FROM golang:1.22-alpine

RUN apk add --no-cache git curl

# Install air (now that Go version is compatible)
RUN go install github.com/air-verse/air@latest

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 8081

CMD ["air"]
