# docker-compose.yml
# Two Postgres shards with automatic failover (repmgr) + pgpool per shard.
# No pgAdmin section (you said you have it locally).
# If you are on native amd64 Linux, you can remove the `platform: linux/amd64` lines.

networks:
  db-net:

volumes:
  shard1-pg-0-data:
  shard1-pg-1-data:
  shard1-pg-2-data:
  shard2-pg-0-data:
  shard2-pg-1-data:
  shard2-pg-2-data:

services:
  # =========================
  # SHARD 1 - PostgreSQL (repmgr)
  # =========================
  shard1-pg-0:
    platform: linux/amd64
    image: public.ecr.aws/bitnami/postgresql-repmgr:latest
    container_name: shard1-pg-0
    restart: unless-stopped
    environment:
      - POSTGRESQL_USERNAME=app
      - POSTGRESQL_PASSWORD=app_pass_shard1
      - POSTGRESQL_DATABASE=appdb
      # quorum sync: 1 synchronous standby; others async
      - POSTGRESQL_SYNCHRONOUS_COMMIT=on
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=1
      # repmgr
      - REPMGR_NODE_NAME=shard1-pg-0
      - REPMGR_NODE_NETWORK_NAME=shard1-pg-0
      - REPMGR_PARTNER_NODES=shard1-pg-0,shard1-pg-1,shard1-pg-2
      - REPMGR_USERNAME=repl
      - REPMGR_PASSWORD=repl_pass
      - REPMGR_PRIMARY_ROLE_WAIT=false
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d appdb"]
      interval: 10s
      timeout: 5s
      retries: 12
    volumes:
      - shard1-pg-0-data:/bitnami/postgresql
    networks: [db-net]

  shard1-pg-1:
    platform: linux/amd64
    image: public.ecr.aws/bitnami/postgresql-repmgr:latest
    container_name: shard1-pg-1
    restart: unless-stopped
    depends_on: [shard1-pg-0]
    environment:
      - POSTGRESQL_USERNAME=app
      - POSTGRESQL_PASSWORD=app_pass_shard1
      - POSTGRESQL_DATABASE=appdb
      - POSTGRESQL_SYNCHRONOUS_COMMIT=on
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=1
      - REPMGR_PRIMARY_HOST=shard1-pg-0
      - REPMGR_NODE_NAME=shard1-pg-1
      - REPMGR_NODE_NETWORK_NAME=shard1-pg-1
      - REPMGR_PARTNER_NODES=shard1-pg-0,shard1-pg-1,shard1-pg-2
      - REPMGR_USERNAME=repl
      - REPMGR_PASSWORD=repl_pass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d appdb"]
      interval: 10s
      timeout: 5s
      retries: 12
    volumes:
      - shard1-pg-1-data:/bitnami/postgresql
    networks: [db-net]

  shard1-pg-2:
    platform: linux/amd64
    image: public.ecr.aws/bitnami/postgresql-repmgr:latest
    container_name: shard1-pg-2
    restart: unless-stopped
    depends_on: [shard1-pg-0]
    environment:
      - POSTGRESQL_USERNAME=app
      - POSTGRESQL_PASSWORD=app_pass_shard1
      - POSTGRESQL_DATABASE=appdb
      - POSTGRESQL_SYNCHRONOUS_COMMIT=on
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=1
      - REPMGR_PRIMARY_HOST=shard1-pg-0
      - REPMGR_NODE_NAME=shard1-pg-2
      - REPMGR_NODE_NETWORK_NAME=shard1-pg-2
      - REPMGR_PARTNER_NODES=shard1-pg-0,shard1-pg-1,shard1-pg-2
      - REPMGR_USERNAME=repl
      - REPMGR_PASSWORD=repl_pass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d appdb"]
      interval: 10s
      timeout: 5s
      retries: 12
    volumes:
      - shard1-pg-2-data:/bitnami/postgresql
    networks: [db-net]

  # Connection pool + stable writer/reader endpoint for Shard 1
  shard1-pgpool:
    platform: linux/amd64
    image: public.ecr.aws/bitnami/pgpool:latest
    container_name: shard1-pgpool
    restart: unless-stopped
    depends_on:
      - shard1-pg-0
      - shard1-pg-1
      - shard1-pg-2
    environment:
      - PGPOOL_BACKEND_NODES=0:shard1-pg-0:5432,1:shard1-pg-1:5432,2:shard1-pg-2:5432
      - PGPOOL_SR_CHECK_USER=repl
      - PGPOOL_SR_CHECK_PASSWORD=repl_pass
      - PGPOOL_POSTGRES_USERNAME=app
      - PGPOOL_POSTGRES_PASSWORD=app_pass_shard1
      - PGPOOL_ENABLE_LOAD_BALANCING=yes
    healthcheck:
      test: ["CMD-SHELL", "</dev/tcp/127.0.0.1/5432"]
      interval: 15s
      timeout: 3s
      retries: 10
    ports:
      - "6433:5432"
    networks: [db-net]

  # =========================
  # SHARD 2 - PostgreSQL (repmgr)
  # =========================
  shard2-pg-0:
    platform: linux/amd64
    image: public.ecr.aws/bitnami/postgresql-repmgr:latest
    container_name: shard2-pg-0
    restart: unless-stopped
    environment:
      - POSTGRESQL_USERNAME=app
      - POSTGRESQL_PASSWORD=app_pass_shard2
      - POSTGRESQL_DATABASE=appdb
      - POSTGRESQL_SYNCHRONOUS_COMMIT=on
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=1
      - REPMGR_NODE_NAME=shard2-pg-0
      - REPMGR_NODE_NETWORK_NAME=shard2-pg-0
      - REPMGR_PARTNER_NODES=shard2-pg-0,shard2-pg-1,shard2-pg-2
      - REPMGR_USERNAME=repl
      - REPMGR_PASSWORD=repl_pass
      - REPMGR_PRIMARY_ROLE_WAIT=false
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d appdb"]
      interval: 10s
      timeout: 5s
      retries: 12
    volumes:
      - shard2-pg-0-data:/bitnami/postgresql
    networks: [db-net]

  shard2-pg-1:
    platform: linux/amd64
    image: public.ecr.aws/bitnami/postgresql-repmgr:latest
    container_name: shard2-pg-1
    restart: unless-stopped
    depends_on: [shard2-pg-0]
    environment:
      - POSTGRESQL_USERNAME=app
      - POSTGRESQL_PASSWORD=app_pass_shard2
      - POSTGRESQL_DATABASE=appdb
      - POSTGRESQL_SYNCHRONOUS_COMMIT=on
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=1
      - REPMGR_PRIMARY_HOST=shard2-pg-0
      - REPMGR_NODE_NAME=shard2-pg-1
      - REPMGR_NODE_NETWORK_NAME=shard2-pg-1
      - REPMGR_PARTNER_NODES=shard2-pg-0,shard2-pg-1,shard2-pg-2
      - REPMGR_USERNAME=repl
      - REPMGR_PASSWORD=repl_pass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d appdb"]
      interval: 10s
      timeout: 5s
      retries: 12
    volumes:
      - shard2-pg-1-data:/bitnami/postgresql
    networks: [db-net]

  shard2-pg-2:
    platform: linux/amd64
    image: public.ecr.aws/bitnami/postgresql-repmgr:latest
    container_name: shard2-pg-2
    restart: unless-stopped
    depends_on: [shard2-pg-0]
    environment:
      - POSTGRESQL_USERNAME=app
      - POSTGRESQL_PASSWORD=app_pass_shard2
      - POSTGRESQL_DATABASE=appdb
      - POSTGRESQL_SYNCHRONOUS_COMMIT=on
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=1
      - REPMGR_PRIMARY_HOST=shard2-pg-0
      - REPMGR_NODE_NAME=shard2-pg-2
      - REPMGR_NODE_NETWORK_NAME=shard2-pg-2
      - REPMGR_PARTNER_NODES=shard2-pg-0,shard2-pg-1,shard2-pg-2
      - REPMGR_USERNAME=repl
      - REPMGR_PASSWORD=repl_pass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d appdb"]
      interval: 10s
      timeout: 5s
      retries: 12
    volumes:
      - shard2-pg-2-data:/bitnami/postgresql
    networks: [db-net]

  # Connection pool + stable writer/reader endpoint for Shard 2
  shard2-pgpool:
    platform: linux/amd64
    image: public.ecr.aws/bitnami/pgpool:latest
    container_name: shard2-pgpool
    restart: unless-stopped
    depends_on:
      - shard2-pg-0
      - shard2-pg-1
      - shard2-pg-2
    environment:
      - PGPOOL_BACKEND_NODES=0:shard2-pg-0:5432,1:shard2-pg-1:5432,2:shard2-pg-2:5432
      - PGPOOL_SR_CHECK_USER=repl
      - PGPOOL_SR_CHECK_PASSWORD=repl_pass
      - PGPOOL_POSTGRES_USERNAME=app
      - PGPOOL_POSTGRES_PASSWORD=app_pass_shard2
      - PGPOOL_ENABLE_LOAD_BALANCING=yes
    healthcheck:
      test: ["CMD-SHELL", "</dev/tcp/127.0.0.1/5432"]
      interval: 15s
      timeout: 3s
      retries: 10
    ports:
      - "7433:5432"
    networks: [db-net]
