@startuml
!include <C4/C4_Container>

Container(apiGateway, "API Gateway")
Container(kafka, "Kafka", "")
Container(mediaService, "Media Service", "Uploads/serves media via REST")
Container(notificationService, "Notification Service", "")

System_Boundary(MessageSystem, "Message Service") {
    Container(MessageService, "Message Service", "Processes messages")
    ContainerDb(redis, "Redis")
    ContainerDb(pgSQL, "PostgreSQL")
}

Rel(apiGateway, MessageService, "request", "REST")
Rel(MessageService, redis, "store popular chats")
Rel(MessageService, pgSQL, "store messages")
Rel(MessageService, mediaService, "upload media", "REST")
Rel(MessageService, kafka, "publish: messages.created")
Rel(kafka, notificationService, "consume: messages.created")

@enduml
